import UIKit

class Iphone13ProMax3ViewController: UIViewController, Storyboarded {
	var coordinator: MainCoordinator?

	// MARK: - Properties
	@IBOutlet private weak var image5ImageView: UIImageView!
	@IBOutlet private weak var frame1View: UIView!
	@IBOutlet private weak var vectorImageView: UIImageView!
	@IBOutlet private weak var accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabel: UILabel!
	@IBOutlet private weak var frame2View: UIView!
	@IBOutlet private weak var vectorImageView2: UIImageView!
	@IBOutlet private weak var rectangle11View: UIView!
	@IBOutlet private weak var watchOnVrLabel: UILabel!

	override func viewDidLoad() {
		super.viewDidLoad()
		setupViews()
		setupLayout()
	}

	override func viewDidLayoutSubviews() {
		super.viewDidLayoutSubviews()
		setupSubViews()
	}

}

extension Iphone13ProMax3ViewController {
	private func setupViews() {

		self.view.backgroundColor = UIColor.daisy2


		image5ImageView.layer.opacity = 1


		frame1View.layer.cornerRadius = 10
		frame1View.layer.masksToBounds =  true
		frame1View.backgroundColor = UIColor.cerulean_70
		frame1View.layer.opacity = 1


		vectorImageView.layer.opacity = 1


		accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabel.layer.opacity = 1
		let accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelText = NSLocalizedString("accommodation.5080.people.location.silbsy.2nd.floo", comment: "")

		let accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelParagraphStyle = NSMutableParagraphStyle()
		accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelParagraphStyle.alignment = .left
		let accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelAttribute: [NSAttributedString.Key: Any] = [ 
			.foregroundColor : UIColor.black,
			.font : UIFont.textStyle9,
			.paragraphStyle : accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelParagraphStyle,
			]
		let accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelAttributedString = NSMutableAttributedString(string: accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelText, attributes: accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelAttribute) 
		accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelAttributedString.addAttributes([ NSAttributedString.Key.foregroundColor : UIColor.black,
			NSAttributedString.Key.font : UIFont.textStyle10,
		], range: NSRange(location: 17, length: 10))
		accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelAttributedString.addAttributes([ NSAttributedString.Key.foregroundColor : UIColor.black,
			NSAttributedString.Key.font : UIFont.textStyle10,
		], range: NSRange(location: 27, length: 1))
		accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelAttributedString.addAttributes([ NSAttributedString.Key.foregroundColor : UIColor.black_50,
			NSAttributedString.Key.font : UIFont.textStyle9,
		], range: NSRange(location: 76, length: 1))
		accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelAttributedString.addAttributes([ NSAttributedString.Key.foregroundColor : UIColor.black_50,
			NSAttributedString.Key.font : UIFont.textStyle10,
		], range: NSRange(location: 76, length: 457))
		accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelAttributedString.addAttributes([ NSAttributedString.Key.foregroundColor : UIColor.black_50,
			NSAttributedString.Key.font : UIFont.textStyle10,
		], range: NSRange(location: 533, length: 35))
		accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabel.attributedText = accommodation5080PeopleLocationSilbsy2ndFloorTypeChemistryLabWelcomeToOurStateoftheartChemistryLabConvenientlyLocatedOnTheSecondFloorDesignedToAccommodate5080PeopleThisVibrantSpacePrioritizesInnovationAndSafetyWhetherYoureAStudentOrFacultyMemberYoullFindModernFacilitiesThatFosterLearningExperimentationAndDiscoveryUseOurAppToNavigateTheCampusAndExploreNotJustLocationsButAlsoTheDynamicCommunityOfThinkersAndMakersReadyToChangeTheWorldHeadOfChemistry256xxxxxxxLabelAttributedString


		frame2View.layer.cornerRadius = 10
		frame2View.layer.masksToBounds =  true
		frame2View.backgroundColor = UIColor.black_50
		frame2View.layer.opacity = 1


		vectorImageView2.layer.opacity = 1


		rectangle11View.layer.cornerRadius = 22
		rectangle11View.layer.masksToBounds =  true
		rectangle11View.backgroundColor = UIColor.cerulean
		rectangle11View.layer.opacity = 1


		watchOnVrLabel.layer.opacity = 1
		watchOnVrLabel.textColor = UIColor.daisy2
		watchOnVrLabel.numberOfLines = 0
		watchOnVrLabel.font = UIFont.textStyle6
		watchOnVrLabel.textAlignment = .center
		watchOnVrLabel.text = NSLocalizedString("watch.on.vr", comment: "")



	}

	private func setupSubViews() {


	}

	private func setupLayout() {
		//Constraints are defined in Storyboard file.
	}

}